## Sheetal Mahajan_20MAI0066

## KNN and Decision Tree

In [1]:
# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Read the dataset onto a variable
train=pd.read_csv("D:\\College\\sem2\\Data warehosing and mining\\Lab\\titanic_dataset.csv") #titanic dataset
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [5]:
#Fix the Predictor Variables
data=train[['Survived','Pclass','Sex','Age','Fare']]

In [6]:
#Change male to '1' and female to '0'
data["Sex"]=df["Sex"].apply(lambda sex:1 if sex=="male" else 0)

In [7]:
data['Sex'].value_counts()

1    577
0    314
Name: Sex, dtype: int64

In [8]:
#Handling the Missing Values -  Data Imputation
data.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [9]:
#Outliners
data['Age']=data['Age'].fillna(data['Age'].median()) 


In [10]:
#Take a look at the Dataframe
data.head(10)

Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500
5         0       3    1  28.0   8.4583
6         0       1    1  54.0  51.8625
7         0       3    1   2.0  21.0750
8         1       3    0  27.0  11.1333
9         1       2    0  14.0  30.0708

In [11]:
#Set the Predictor(x) and Response(Y) variables
X=data.drop("Survived", axis=1)
Y=data["Survived"]

In [13]:
#Splitting into training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25, random_state=40)

### 1. KNN Classification Algorithm:

K-nearest neighbors (KNN) algorithm is a type of supervised ML algorithm which can be used for both classification as well as regression predictive problems. However, it is mainly used for classification predictive problems in industry. The following two properties would define KNN well −

1. Lazy learning algorithm − KNN is a lazy learning algorithm because it does not have a specialized training phase and uses all the data for training while classification.

2. Non-parametric learning algorithm − KNN is also a non-parametric learning algorithm because it doesn’t assume anything about the underlying data.

In k-NN classification, the output is a class membership. An object is classified by a plurality vote of its neighbors, with the object being assigned to the class most common among its k nearest neighbors (k is a positive integer, typically small). If k = 1, then the object is simply assigned to the class of that single nearest neighbor. In k-NN regression, the output is the property value for the object. This value is the average of the values of k nearest neighbors.

In [14]:
#K Nearest Neighbor Model
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=15)

In [15]:
#Compute the Predictions
Y_pred_k=knn.predict(X_test)
Y_pred_k

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1], dtype=int64)

In [16]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_knn=confusion_matrix(Y_test,Y_pred_k)
cm_knn

array([[99, 29],
       [44, 51]], dtype=int64)

In [17]:
confusion_knn=pd.crosstab(Y_pred_k,Y_test,rownames=['predicted'],colnames=['actual'])
print("\n The Confusion Matrix is:")
confusion_knn


 The Confusion Matrix is:


actual      0   1
predicted        
0          99  44
1          29  51

In [18]:
#Confusion Matrix
from sklearn.metrics import accuracy_score
accuracy_knn=accuracy_score(Y_test,Y_pred_k)
print("Accuracy using K Nearest Neighbor Model is: ",accuracy_knn)

Accuracy using K Nearest Neighbor Model is:  0.672645739910314


In [19]:
#Classification Report
from sklearn.metrics import classification_report
report=classification_report(Y_test,Y_pred_k)
print(report)

              precision    recall  f1-score   support

           0       0.69      0.77      0.73       128
           1       0.64      0.54      0.58        95

    accuracy                           0.67       223
   macro avg       0.66      0.66      0.66       223
weighted avg       0.67      0.67      0.67       223



### 2. Decision Tree :


Decision tree is the most powerful and popular tool for classification and prediction. A Decision tree is a flowchart like tree structure, where each internal node denotes a test on an attribute, each branch represents an outcome of the test, and each leaf node (terminal node) holds a class label.
A decision tree is a map of the possible outcomes of a series of related choices. It allows an individual or organization to weigh possible actions against one another based on their costs, probabilities, and benefits.
As the name goes, it uses a tree-like model of decisions. They can be used either to drive informal discussion or to map out an algorithm that predicts the best choice mathematically.
A decision tree typically starts with a single node, which branches into possible outcomes. Each of those outcomes leads to additional nodes, which branch off into other possibilities. This gives it a tree-like shape.

In [20]:
# Call the Decision Tree Model
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(max_depth=10, random_state=101, max_features=None, min_samples_leaf=15)
dtree.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=15, random_state=101)

In [21]:
#Compute the Predictions or Y hat
Y_pred_d= dtree.predict(X_test)
Y_pred_d

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0], dtype=int64)

In [22]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_d=confusion_matrix(Y_test,Y_pred_d)
cm_d

array([[114,  14],
       [ 27,  68]], dtype=int64)

In [23]:
confusion_d=pd.crosstab(Y_pred_d,Y_test,rownames=['predicted'],colnames=['actual'])
print("\n The Confusion Matrix is:")
confusion_d


 The Confusion Matrix is:


actual       0   1
predicted         
0          114  27
1           14  68

In [24]:
#Accuracy Score
from sklearn.metrics import accuracy_score
accuracy_dtree=accuracy_score(Y_test,Y_pred_d)
print("Accuracy using Decision Tree Model is: ",accuracy_dtree)

Accuracy using Decision Tree Model is:  0.8161434977578476


In [25]:
#Classification Report
from sklearn.metrics import classification_report
report=classification_report(Y_test,Y_pred_d)
print(report)

              precision    recall  f1-score   support

           0       0.81      0.89      0.85       128
           1       0.83      0.72      0.77        95

    accuracy                           0.82       223
   macro avg       0.82      0.80      0.81       223
weighted avg       0.82      0.82      0.81       223

